- name: Generate wireguard preshared key
  shell: "wg genpsk"
  register: preshared_key

- name: Create a directory if it does not exist
  file:
    path: "{{ peer_params.preshared_key | dirname }}"
    state: directory
    mode: '0750'

- name: Encrypt and store preshared key
  shell: "echo {{ preshared_key.stdout }} | ansible-vault encrypt - > {{ peer_params.preshared_key }}"