- name: Generate wireguard private key
  shell: "wg genkey"
  register: private_key

- name: Create a directory if it does not exist
  file:
    path: "{{ peer_params.private_key | dirname }}"
    state: directory
    mode: '0750'

- name: Encrypt and store private key
  shell: "echo {{ private_key.stdout }} | ansible-vault encrypt - > {{ peer_params.private_key }}"