- name: Generate wireguard public key from private key
  shell: "ansible-vault decrypt --output=- {{ peer_params.private_key }} | wg pubkey"
  register: public_key

- name: Create a directory if it does not exist
  file:
    path: "{{ peer_params.public_key | dirname }}"
    state: directory
    mode: '0750'

- name: Encrypt and store public key
  shell: "echo {{ public_key.stdout }} | ansible-vault encrypt - > {{ peer_params.public_key }}"